name: SAST workflow
on:
  workflow_call:
    inputs:
      project-action-path:
        description: 'Path to the project specific action'
        required: true
        type: string
      unc-branch-enabled:
        description: 'UNC branch enabled'
        required: true
        type: boolean
        default: true
    secrets:
      SAST_ACTION_KEY:
        description: 'Key to access SAST action'
        required: true
      UNC_ACTION_KEY:
        description: 'Key to access UNC action'
        required: true
      SAST_URL:
        description: 'SAST URL'
        required: true
      SAST_TEAM:
        description: 'SAST Team'
        required: true
      SAST_USERNAME:
        description: 'SAST Username'
        required: true
      SAST_PASSWORD:
        description: 'SAST Password'
        required: true
      SAST_CLIENT_SECRET:
        description: 'SAST Client Secret'
        required: true
env:
  project-action-move-cmd: |
    mv .github/workflows/sast/action/actions/${{ inputs.project-action-path }}/action.yml .github/workflows/sast/action/action.yml
  action-path: |
    actions/${{ inputs.project-action-path }}/action.yml
jobs:
  authorize:
    environment:
      ${{(github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'External' || 'Internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  sast:
    needs: authorize
    runs-on: sast
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          ref: ${{github.event.pull_request.head.sha || github.ref}}
          persist-credentials: 'false' #By default, actions/checkout persists GIT credentials, we do not need this
      # Checking out SAST composite action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sast-configs
          ref: main
          ssh-key: ${{ secrets.SAST_ACTION_KEY }}
          path: .github/workflows/sast
          # Checking out only SAST action and composite project configuration action
          sparse-checkout: |
            base/sast-action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sast-configs
          ref: main
          ssh-key: ${{ secrets.SAST_ACTION_KEY }}
          path: .github/workflows/sast/action
          # Checking out only SAST action and composite project configuration action
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ env.action-path }}
      - name: Move action
        env:
          ACTION: ${{ inputs.project-action-path }}
        run: |
          echo $ACTION
          echo ${ACTION}
          full_path=".github/workflows/sast/action/actions/$ACTION/action.yml"
          mv $full_path .github/workflows/sast/action/action.yml
      - uses: ./.github/workflows/sast/action
        with:
          SAST_TEAM: ${{ secrets.SAST_TEAM }}
          SAST_URL: ${{ secrets.SAST_URL }}
          SAST_USERNAME: ${{ secrets.SAST_USERNAME }}
          SAST_PASSWORD: ${{ secrets.SAST_PASSWORD }}
          SAST_CLIENT_SECRET: ${{ secrets.SAST_CLIENT_SECRET }}
          UNC_ACTION_KEY: ${{ secrets.UNC_ACTION_KEY }}
          UNC_BRANCH_ENABLED: ${{ inputs.unc-branch-enabled }}


