name: SCA workflow
on:
  workflow_call:
    inputs:
      project-action-path:
        description: 'Path to the project specific action'
        required: true
        type: string
    secrets:
      SCA_API_TOKEN:
        description: 'SCA API token'
        required: true
      SCA_URL:
        description: 'SCA instance URL'
        required: true
      SCA_ACTION_KEY:
        description: 'SCA action access key'
        required: true
      UNC_ACTION_KEY:
        description: 'UNC action access key'
        required: true
env:
  action-path: |
    actions/${{ inputs.project-action-path }}/action.yml
jobs:
  authorize:
    environment:
      ${{(github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'External' || 'Internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  sca-full:
    needs: authorize
    runs-on: sca
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          persist-credentials: 'false' #By default, actions/checkout persists GIT credentials, we do not need this
      # Checking out SCA base composite action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sca-configs
          ref: main
          ssh-key: ${{ secrets.SCA_ACTION_KEY }}
          path: .github/workflows/sca
          persist-credentials: 'false'
          # Checking out only SCA action
          sparse-checkout: |
            base/sca-action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sca-configs
          ref: main
          ssh-key: ${{ secrets.SCA_ACTION_KEY }}
          path: .github/workflows/sca/action
          persist-credentials: 'false'
          # Checking out only project configuration action
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ env.action-path }}
      - name: Move action
        env:
          ACTION: ${{ inputs.project-action-path }}
        run: |
          full_path=".github/workflows/sca/action/actions/$ACTION/action.yml"
          mv $full_path .github/workflows/sca/action/action.yml
      - uses: ./.github/workflows/sca/action
        with:
          SCA_URL: ${{ secrets.SCA_URL }}
          SCA_API_TOKEN: ${{ secrets.SCA_API_TOKEN }}
          SCA_FULL_SCAN: true
          UNC_ACTION_KEY: ${{ secrets.UNC_ACTION_KEY }}
  sca-rapid:
    needs: authorize
    runs-on: sca
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'pull_request_target'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          ref: ${{github.event.pull_request.head.sha || github.ref}}
          persist-credentials: 'false' #By default, actions/checkout persists GIT credentials, we do not need this
      # Checking out SCA base composite action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sca-configs
          ref: main
          ssh-key: ${{ secrets.SCA_ACTION_KEY }}
          path: .github/workflows/sca
          persist-credentials: 'false'
          # Checking out only SCA action
          sparse-checkout: |
            base/sca-action
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with: 
          repository: NordSecurity/sca-configs
          ref: main
          ssh-key: ${{ secrets.SCA_ACTION_KEY }}
          path: .github/workflows/sca/action
          persist-credentials: 'false'
          # Checking out only project configuration action
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ env.action-path }}
      - name: Move action
        env:
          ACTION: ${{ inputs.project-action-path }}
        run: |
          full_path=".github/workflows/sca/action/actions/$ACTION/action.yml"
          mv $full_path .github/workflows/sca/action/action.yml
      - uses: ./.github/workflows/sca/action
        with:
          SCA_URL: ${{ secrets.SCA_URL }}
          SCA_API_TOKEN: ${{ secrets.SCA_API_TOKEN }}
          SCA_FULL_SCAN: false
          UNC_ACTION_KEY: ${{ secrets.UNC_ACTION_KEY }}
